language: node_js
node_js:
  - "7"
script:
  - yarn lint
  - yarn test:coverage-ci
  - yarn serve:background
  - yarn build
  - yarn test:e2e-remote

cache: yarn
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  sauce_connect: true
