language: node_js
node_js:
  - "7"
script:
  - yarn lint
  - yarn ci-coverage

cache: yarn
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
