const wdio = require("./wdio.config.js");

exports.config = Object.assign({}, wdio.config, {
  capabilities: [{
    build: process.env.TRAVIS_BUILD_NUMBER,
    browserName: "MicrosoftEdge",
    platform: "Windows 10",
    recordVideo: false,
    screenResolution: "1920x1080",
    'tunnel-identifier': process.env.TRAVIS_JOB_NUMBER,
    version: "14.14393",
  },
  {
    build: process.env.TRAVIS_BUILD_NUMBER,
    browserName: "chrome",
    platform: "Windows 8.1",
    recordVideo: false,
    screenResolution: "1920x1080",
    'tunnel-identifier': process.env.TRAVIS_JOB_NUMBER,
    version: "58.0",
  },
  {
    build: process.env.TRAVIS_BUILD_NUMBER,
    browserName: "firefox",
    platform: "Windows 10",
    recordVideo: false,
    screenResolution: "1920x1080",
    'tunnel-identifier': process.env.TRAVIS_JOB_NUMBER,
    version: "53.0",
  },
  {
    build: process.env.TRAVIS_BUILD_NUMBER,
    browserName: "internet explorer",
    platform: "Windows 10",
    recordVideo: false,
    screenResolution: "1920x1080",
    'tunnel-identifier': process.env.TRAVIS_JOB_NUMBER,
    version: "11.103",
  },
  {
    build: process.env.TRAVIS_BUILD_NUMBER,
    browserName: "safari",
    platform: "macOS 10.12",
    recordVideo: false,
    screenResolution: "1400x1050",
    'tunnel-identifier': process.env.TRAVIS_JOB_NUMBER,
    version: "10.0",
  }],
  services: ['sauce'],
  user: process.env.SAUCE_USERNAME,
  key: process.env.SAUCE_ACCESS_KEY,
  sauceConnect: false,
});
