const merge = require("webpack-merge");
const baseConfig = require("./webpack.config.js");
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = merge({
  devtool: 'inline-source-map',
  module: {
    rules: [
      { loader: "source-map-loader", test: /\.js$/, enforce: "pre" },
      { loader: "source-map-loader", test: /\.tsx?$/, enforce: "pre" }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: 'src/index.ejs',
      inject: false, // we don't inject here because we defined our serviceWorker to be defined last in the template
                     // also we handle the import of javascript chunk files generated by webpack manually
    })
  ]
}, baseConfig);
